import { Inter } from "next/font/google";
import "./globals.css";
import { ChakraProvider } from "@chakra-ui/react";
import Navbar from "./components/common/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <ChakraProvider>
                {/* <Provider store={store}> */}
                <div className="borde-2 border-red-500">
                    <Navbar />
                    <body className={inter.className}>{children}</body>
                </div>
                {/* </Provider> */}
            </ChakraProvider>
        </html>
    );
}
