import { Inter } from "next/font/google";
import "./globals.css";
import { ChakraProvider } from "@chakra-ui/react";
import Providers from "../redux/Provider";
import Navbar from "./components/common/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <Providers>
                <ChakraProvider>
                    <div className="borde-2 border-red-500">
                        <Navbar />
                        <body className={`${inter.className} mt-[82px]`}>
                            {/* <div className="min-h-[91vh] border-4 border-yellow-800"> */}
                            {children}
                            {/* </div> */}
                        </body>
                    </div>
                </ChakraProvider>
            </Providers>
        </html>
    );
}
